# Configuration file for the Sphinx documentation builder.
#
# PyAE - Python for After Effects Documentation

import sys
from pathlib import Path

# -- Path setup --------------------------------------------------------------

# Add PyAE stub files to Python path for autodoc
sys.path.insert(0, str(Path(__file__).parent.parent / 'PyAE' / 'ae-stubs'))

# -- Project information -----------------------------------------------------

project = 'PyAE'
copyright = '2026, VTech Studio'
author = 'VTech Studio'
version = '1.0'
release = '1.0.0'

# -- General configuration ---------------------------------------------------

extensions = [
    'sphinx.ext.autodoc',           # Auto-generate documentation from docstrings
    'sphinx.ext.napoleon',          # Support for Google/NumPy style docstrings
    'sphinx.ext.intersphinx',       # Link to other documentation
    'myst_parser',                  # Markdown support
    'sphinxcontrib.mermaid',        # Mermaid diagram support
]

# Mock imports for modules that can't be imported during build
# ae module is a C++ extension that only works inside After Effects
autodoc_mock_imports = ['ae', 'ae.sdk', 'ae.render_queue']

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store', '.venv', 'README.md']

# The language for content autogenerated by Sphinx.
language = 'ja'

# Suppress specific warnings that don't affect documentation quality
suppress_warnings = [
    'ref.doc',           # Unknown document references (external/future docs)
]

# -- Options for Napoleon (Google/NumPy style docstrings) -------------------

napoleon_google_docstring = True
napoleon_numpy_docstring = False
napoleon_include_init_with_doc = True
napoleon_include_private_with_doc = False
napoleon_include_special_with_doc = True
napoleon_use_admonition_for_examples = True
napoleon_use_admonition_for_notes = True
napoleon_use_admonition_for_references = False
napoleon_use_ivar = False
napoleon_use_param = True
napoleon_use_rtype = True
napoleon_preprocess_types = True
napoleon_attr_annotations = True

# -- Options for HTML output -------------------------------------------------

html_theme = 'sphinx_rtd_theme'
html_static_path = ['_static']

html_theme_options = {
    'navigation_depth': 4,
    'collapse_navigation': False,
    'sticky_navigation': True,
    'includehidden': True,
    'titles_only': False,
}

# -- Options for intersphinx -------------------------------------------------

intersphinx_mapping = {
    'python': ('https://docs.python.org/3', None),
}

# -- Options for Markdown support (MyST) -------------------------------------

myst_enable_extensions = [
    'colon_fence',      # ::: syntax for directives
    'deflist',          # Definition lists
    'tasklist',         # Task lists
]

# -- Options for Mermaid diagrams ---------------------------------------------

mermaid_output_format = 'raw'  # Output as raw mermaid code for client-side rendering
myst_fence_as_directive = ['mermaid']  # Allow ```mermaid code blocks

source_suffix = {
    '.rst': 'restructuredtext',
    '.md': 'markdown',
}
